name: CI
on:
  push:
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: make install

      - name: Lint (flake8)
        run: make lint

      - name: Format (black)
        run: make format

      - name: Tests (pytest)
        run: make test

      - name: Run analysis
        run: make analyze
